language: node_js
node_js:
- '6.11'
- '8.8'
before_script: ./scripts/before_script.sh
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_JOB_NUMBER = $TRAVIS_BUILD_NUMBER.1"
    repo: parse-community/parse-dashboard
  email:
    secure: NVlNLZh4bsCUaO1qYdXp6DpYnISQIXqz0xIaMfPI06CqFErkqlodWD7aOOYT2LyKos1f9QbQBbURl27drtJLudNqIXfMFbWMc0MwDJp4fJBa6vRFdn1jYNDcrqTbdAAoH5z6SU4r7YdiPz5pIJ7XjMajryaB7dAZLNiuZaTeTboF6QEQj+j+bw9IMcuiDIxQt3t+5f9Raah1HwZX5h5CBXS8voE97deCpf6jdVt3gaKvnZGvTvnDfYBsvmDE2ueqFK/xjt240PMArxqTbkEVFl/7Gti5jurLIKtX7StNsEZZZiGJS2+E9Px5nSFMM3JKnfD5Cj6IZxqobL9mQ4KueaL3tX5BOnbHfSpJs2t3Lp8TO0hnpmn8w/d7pekOjH3LihgC7AbZ3/ark9ZvPvP63XKhivKL4NuvNa+8yHeQNOLIzOjTPZl7ZS6XkibwxsOtgasMQWK4/Ttg6/jHHPjaXbnqn7ZoIM2GPZBv22xaReIWSRJdgW8G9ceSBEIIZFONkKsH0apDDq3eHg0vNEI4R3oEmV6t/R9yvpCzarfNLn5+l80ztMM+rX91eXT8B5V8Mpy+7urbQwIoFLUGRPDxbofEqEm8S6sLsjyYe7VnxBC4Lhir3DFxYL0+q5YLfhq64AejA4BM65+v5SyvXCUvyakzsRsydU230sJyaONHD5I=
  api_key:
    secure: k3c9OMqlY5fZ4E+G1IataTfChw+Qyd3b/VkoQiKri6AD795RKKB4lfV69PyfQJ2Mlw8nKp8CkQKYPRgf8as23xg4XSNkoaQOeL5kTRFuN+T5BEEoS/eJVx276csQ0edHfYGwW4rM4AbdPjlr+8CjmNqsYRmCXHYF5HiNIIaD+Y9fU4hMpx5JZvmVI0NePZzEe4wAFiCQ2doqeXdam808qNHInl2BayZLPZyU7dLAk+CBH+gTL4u9bn2Q4eWwICB8XI2heIm6i9oXJUReSCLY387FyowtGeepH/Q3g6JDxKmZ3qw+biYdyyk9TJdDfPUcjWHDlD+pQAHiBOUtxLh+5wVi9lIYaYHJDC74KRPmxgKyTvGf41z7q8IcK9dc3Eu5JIqtGmzpkCHYBHHkQ29W75sHOW8OuI/7VAZDr5pjZqU7LE9dHuk2Da8EccJQ1WHkBul3Tt36YWL1TtsgyE+PbpxOdq72+71Ji0Zh3O6udgVqBEZKFz6Fow7cMUUTWCy5oMSPdjqwW3C/jyB2tpliZfX1Lq+hysCwAjuKNhegyOwOGshf9xW0JcjBcHN+Q6fCaKlN8R/MRkMk1CRcbzxwt4SMKIskR/YgmbJ0ozaC5uI/HkKKpno+VTjPRKpzFBBA6L+ZWnt+0KLsjOjO6ITF1WjAfHK9lBBLjd87jWgsBBE=
